### ISSUE TITLE
Changing XML to match req spec data struct

### ISSUE THREAD

**Issue by SunyataZero** [MettaCenter/DailyMettaApp#12]
#### Req spec data structure
- Date
- Wisdom teacher
- Link to the article on the web
- Article text
  - Title
  - Quote
  - Main text
  - Experiment in Nonviolence
- _Excluded:_ Any media seen on the web (images or videos)
#### What we may wish to change in the Atom feed
- Adding a tag with the name of the wisdom teacher (since Stephanie explained to me that the idea is that each year will have a new wisdom teacher)
- Creating separate tags for the quote and the experiment in nonviolence (assuming that we are going to keep this way of presenting structuring the articles)

**Comment by jimsky7** [comment]
I do not have enough bandiwth to check what this item #12 is about, however if you can go with theXML  structure WordPress provides, it will be 1000% easy. There are WP plugins we can use to augment that structure too.

See if you can take a look at the existing category feed for daily-metta and work with what is there.

-Sky

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

**Comment by SunyataZero** [comment]
Closing this issue since we don't need to make any changes (except maybe the date for which there is a separate issue here in github)
