### ISSUE TITLE
Using the feed categories in the app?

### ISSUE THREAD

**Issue by SunyataZero** [MettaCenter/DailyMettaApp#14]
Do we want to use the category tags in our app? These are already available in the Atom feed

**Comment by jimsky7** [comment]
I will look at XML feed mods you have requested, when I return on the 6th or after.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

**Comment by SunyataZero** [comment]
After talking with Michael and Stephanie today we have decided that we don't want this feature, it's enough with text search, also it doesn't fit the common usage of the app
