### ISSUE TITLE
Creating a Google Play dev account for Metta Center?

### ISSUE THREAD

**Issue by SunyataZero** [MettaCenter/DailyMettaApp#23]
Or are we going to use Tord's account? (fine by him)
Advantages of having a separate account:
- Legal issues
- **In the future other's might take over the project and don't want to ask Tord each time they lik to update something**

**Comment by jimsky7** [comment]
For the sake of institutional continuity it is best for Metta Center to have its own account. You would be surprised how hard these things would be to “round up” five years out in the future when Tord has moved to Iceland and is no longer answering his email.

---

Sky (Jim Schuyler, PhD)
—The future has arrived, and the label says “some assembly required.” 
Blog: http://blog.red7.com/
Phone: +1.415.759.7337
PGP Keys: http://web.red7.com/pgp
