### ISSUE TITLE
How do we deal with web links?

### ISSUE THREAD

**Issue by SunyataZero** [MettaCenter/DailyMettaApp#24]
Links can be..
- ..links inside the text
- ..the link to the online article

Are the links..
- ..always shown
- ..never shown
- ..or shown only when we have internet access?

**Comment by jimsky7** [comment]
Always show links. People may want to copy-paste them for later reference.

---

Sky (Jim Schuyler, PhD)
—The future has arrived, and the label says “some assembly required.” 
Blog: http://blog.red7.com/
Phone: +1.415.759.7337
PGP Keys: http://web.red7.com/pgp

**Comment by SunyataZero** [comment]
This was more complicated than i thought at first, for details please see the code comment in ArticleFragmentC.java
But it is now fixed, closing

**Comment by prashant-nema** [comment]
Thanks. this seem to work now for all cases I tried.  If it is link to another DailyMetta article do we want to still stay in the app?

**Comment by SunyataZero** [comment]
~~Thanks! Which cases didn't it work for? It should work each time there is
an "<a>" link embedded in the html~~ EDIT: Removed this because Prashant updated from "most cases" to "all cases"

It would be nice to have links internal to the app, but i'm thinking that
this might be an unusual case and that it's a bit difficult to implement.
However, please feel very free to write an issue on this for the backlog so
we can deal with it later

Kind Regards, Tord

On Wed, Jul 22, 2015 at 5:01 AM, prashant-nema notifications@github.com
wrote:

> Thanks. this seem to work now for most cases I tried. If it is link to
> another DailyMetta article do we want to still stay in the app?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MettaCenter/DailyMettaApp/issues/24#issuecomment-123548440
> .

## 

Beyond our ideas of right and wrong doing there is a field, I'll meet you
there
-- Rumi
http://ihavearrived.org/

**Comment by jimsky7** [comment]
It does seem to me that if a link is legitimately to another Daily Metta article it should stay in the app, if possible.

Each XML entry, by the way, should have a “canonical URL” in it, telling the external URL that can be used to reference the original article. This could be picked up by the app from the XML stream and used internally to link to other Daily Metta articles.

Here are a few such links from today's XML feed. Each such link is within an <entry> object within the Atom XML feed as read early this morning.

```
    <link rel="alternate" type="text/html" href="http://mettacenter.org/daily-metta/nonviolence-to-overcome-terror-daily-metta/" />
    <link rel="alternate" type="text/html" href="http://mettacenter.org/daily-metta/making-progress-understanding-conflict-daily-metta/" />
    <link rel="alternate" type="text/html" href="http://mettacenter.org/daily-metta/mirror-neurons-and-nonviolence-daily-metta/" />
    <link rel="alternate" type="text/html" href="http://mettacenter.org/daily-metta/wisdom-and-sugar-daily-metta/" />
```

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

**Comment by SunyataZero** [comment]
Ok, i've reopened this issue now, maybe Eliane will have some ideas for us as well
