### ISSUE TITLE
One-way sync of Atom/RSS data into SQLite in Android

### ISSUE THREAD

**Issue by SunyataZero** [MettaCenter/DailyMettaApp#30]
http://stackoverflow.com/questions/ask

One-way sync of Atom/RSS data into SQLite in Android - best way to do this?

Hi all, what is the best way to sync Atom/RSS data from a server into an SQLite database in Android? What i'd like to achieve is to end up with the data on the server in the local SQLite db. The thing is that new entries are added every day to the online db, and it might take a while between the user connects to 

I have already managed to download and parse the data, but the trick is to make sure that all entries in the Atom feed we have on the server side

**Comment by jimsky7** [comment]
I was able to set the number of items returned in Atom/RSS/XML feeds to 25 today. It was a bit tricky and it affects all feeds, but does not changed the number of items returned "per page" within the actual web site. That was the tricky part -- making sure it only affects the feed. I am still looking for a way you can add something to the feed URL itself to change the number of items returned, but for now it's 25 items that will be returned. Incidentally, the feed is currently 209K when it includes 25 items, so this is not practical long term for mobile users.

**Comment by SunyataZero** [comment]
209K for only 25 items?? Alright, at least what will be saved in the db is
a lot less (roughly one fourth of that). I can see that the article text
itself is repeated in the Atom feed, is this something that can be removed?
Kind Regards, Tord

On Thu, Aug 6, 2015 at 11:42 PM, Sky notifications@github.com wrote:

> I was able to set the number of items returned in Atom/RSS/XML feeds to 25
> today. It was a bit tricky and it affects all feeds, but does not changed
> the number of items returned "per page" within the actual web site. That
> was the tricky part -- making sure it only affects the feed. I am still
> looking for a way you can add something to the feed URL itself to change
> the number of items returned, but for now it's 25 items that will be
> returned. Incidentally, the feed is currently 209K when it includes 25
> items, so this is not practical long term for mobile users.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128517959
> .

## 

Beyond our ideas of right and wrong doing there is a field, I'll meet you
there
-- Rumi

Public PGP key:
https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
http://ihavearrived.org/

**Comment by jimsky7** [comment]
I was able to modify the feeds URL so you can now say how many entries you want. You could request a zillion the first time, then cut back based on the number of days you’ve gone without fetching. I believe you’d call that a kludge, wouldn’t you?

http://mettacenter http://mettacenter/.org /category/daily-metta/feed/atom/?n=2

for example, would get you the most recent two Daily Mettas.

I would like to be able to do this by date, but I don’t have time to look into this today. Since I know I can pick up parameters from the URL, and can pick those up before the database query runs, I know it’s possible. I just have to investigate the proper params to add to the SQL query in order to handle dates.

Catch you later.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

**Comment by jimsky7** [comment]
The article text “repeats” because one is the summary and one is the content. An Atom feed probably should not “guess" that the two are duplicates because they could be different. And in fact one has no HTML and the other does have HTML so it would be hard to know whether they are duplicates or not. Stephanie could provide a separate and shorter summary, perhaps.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

**Comment by SunyataZero** [comment]
This is terrific! I'm very relieved to see that it's working. Yes, i'm
thinking the same as you: The first time the app is launched i will
download everything, and we'll have a variable storing the id or date of
the latest article. Then we'll fetch the same number of articles as days
that has passed since that date. In this way though there's a risk of
problems like you said ("kludge" - what a funny word!). If we want to be
sure we can fetch one extra and compare the id's of the latest we have with
the oldest we fetch

Even better would be to have an id for each Metta where we can trust that
the id is incremented by one for each Daily Metta article. There's already
this tag
<id>http://mettacenter.org/?p=16769</id>
but that is increased more than one (i'm guessing it's for the
mettacenter.org pages or blog posts in general right?). Maybe we could fix
this when dealing with the xml update?

Kind Regards,
Tord

On Fri, Aug 7, 2015 at 12:19 AM, Sky notifications@github.com wrote:

> I was able to modify the feeds URL so you can now say how many entries you
> want. You could request a zillion the first time, then cut back based on
> the number of days you’ve gone without fetching. I believe you’d call that
> a kludge, wouldn’t you?
> 
> http://mettacenter http://mettacenter/.org
> /category/daily-metta/feed/atom/?n=2
> 
> for example, would get you the most recent two Daily Mettas.
> 
> I would like to be able to do this by date, but I don’t have time to look
> into this today. Since I know I can pick up parameters from the URL, and
> can pick those up before the database query runs, I know it’s possible. I
> just have to investigate the proper params to add to the SQL query in order
> to handle dates.
> 
> Catch you later.
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> CyberSpark.net
> -Keeping the flame of free speech
> and human rights alive online
> 
> > On Aug 6, 2015, at 2:47 PM, Tord notifications@github.com wrote:
> > 
> > 209K for only 25 items?? Alright, at least what will be saved in the db
> > is
> > a lot less (roughly one fourth of that). I can see that the article text
> > itself is repeated in the Atom feed, is this something that can be
> > removed?
> > Kind Regards, Tord
> > 
> > On Thu, Aug 6, 2015 at 11:42 PM, Sky notifications@github.com wrote:
> > 
> > > I was able to set the number of items returned in Atom/RSS/XML feeds
> > > to 25
> > > today. It was a bit tricky and it affects all feeds, but does not
> > > changed
> > > the number of items returned "per page" within the actual web site.
> > > That
> > > was the tricky part -- making sure it only affects the feed. I am still
> > > looking for a way you can add something to the feed URL itself to
> > > change
> > > the number of items returned, but for now it's 25 items that will be
> > > returned. Incidentally, the feed is currently 209K when it includes 25
> > > items, so this is not practical long term for mobile users.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128517959
> > > 
> > > .
> > 
> > ## 
> > 
> > Beyond our ideas of right and wrong doing there is a field, I'll meet you
> > there
> > -- Rumi
> > 
> > Public PGP key:
> > 
> > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > http://ihavearrived.org/
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128518920
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128525095
> .

## 

Beyond our ideas of right and wrong doing there is a field, I'll meet you
there
-- Rumi

Public PGP key:
https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
The ID is indeed the database row number of the actual post. They’re not consecutive, as you noticed. They are unique, however.

I should be able to give you a feed-by-date capability in a few days.

---

Sky (Jim Schuyler, PhD)
—The future has arrived, and the label says “some assembly required.” 
Blog: http://blog.red7.com/
Phone: +1.415.759.7337
PGP Keys: http://web.red7.com/pgp

**Comment by SunyataZero** [comment]
Ok, great, one thing i'm worrying about though with using the date instead
of a consecutivly updated id is that it's possible that two articles are
posted on the same day (though unlikely). The date will be important though
since we have "search by date" but that's inside the application and we
have this already. I may be missing something but i'm not sure that we need
to be able to send the date as a parameter to the atom feed (or what
produces the atom feed), does this make sense?
Kind Regards, Tord

On Fri, Aug 7, 2015 at 12:57 AM, Sky sky@red7.com wrote:

> The ID is indeed the database row number of the actual post. They’re not
> consecutive, as you noticed. They are unique, however.
> 
> I should be able to give you a feed-by-date capability in a few days.
> 
> ---
> 
> ---
> 
> Sky (Jim Schuyler, PhD)
> —The future has arrived, and the label says “some assembly required.”
> Blog: http://blog.red7.com/
> Phone: +1.415.759.7337
> PGP Keys: http://web.red7.com/pgp
> 
> On Aug 6, 2015, at 3:46 PM, Tord Dellsén tord.dellsen@gmail.com wrote:
> 
> This is terrific! I'm very relieved to see that it's working. Yes, i'm
> thinking the same as you: The first time the app is launched i will
> download everything, and we'll have a variable storing the id or date of
> the latest article. Then we'll fetch the same number of articles as days
> that has passed since that date. In this way though there's a risk of
> problems like you said ("kludge" - what a funny word!). If we want to be
> sure we can fetch one extra and compare the id's of the latest we have with
> the oldest we fetch
> 
> Even better would be to have an id for each Metta where we can trust that
> the id is incremented by one for each Daily Metta article. There's already
> this tag
> <id>http://mettacenter.org/?p=16769</id>
> but that is increased more than one (i'm guessing it's for the
> mettacenter.org pages or blog posts in general right?). Maybe we could
> fix this when dealing with the xml update?
> 
> Kind Regards,
> Tord
> 
> On Fri, Aug 7, 2015 at 12:19 AM, Sky notifications@github.com wrote:
> 
> > I was able to modify the feeds URL so you can now say how many entries
> > you want. You could request a zillion the first time, then cut back based
> > on the number of days you’ve gone without fetching. I believe you’d call
> > that a kludge, wouldn’t you?
> > 
> > http://mettacenter http://mettacenter/.org
> > /category/daily-metta/feed/atom/?n=2
> > 
> > for example, would get you the most recent two Daily Mettas.
> > 
> > I would like to be able to do this by date, but I don’t have time to look
> > into this today. Since I know I can pick up parameters from the URL, and
> > can pick those up before the database query runs, I know it’s possible. I
> > just have to investigate the proper params to add to the SQL query in order
> > to handle dates.
> > 
> > Catch you later.
> > 
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > CyberSpark.net
> > -Keeping the flame of free speech
> > and human rights alive online
> > 
> > > On Aug 6, 2015, at 2:47 PM, Tord notifications@github.com wrote:
> > > 
> > > 209K for only 25 items?? Alright, at least what will be saved in the db
> > > is
> > > a lot less (roughly one fourth of that). I can see that the article text
> > > itself is repeated in the Atom feed, is this something that can be
> > > removed?
> > > Kind Regards, Tord
> > > 
> > > On Thu, Aug 6, 2015 at 11:42 PM, Sky notifications@github.com wrote:
> > > 
> > > > I was able to set the number of items returned in Atom/RSS/XML feeds
> > > > to 25
> > > > today. It was a bit tricky and it affects all feeds, but does not
> > > > changed
> > > > the number of items returned "per page" within the actual web site.
> > > > That
> > > > was the tricky part -- making sure it only affects the feed. I am
> > > > still
> > > > looking for a way you can add something to the feed URL itself to
> > > > change
> > > > the number of items returned, but for now it's 25 items that will be
> > > > returned. Incidentally, the feed is currently 209K when it includes 25
> > > > items, so this is not practical long term for mobile users.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128517959
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Beyond our ideas of right and wrong doing there is a field, I'll meet
> > > you
> > > there
> > > -- Rumi
> > > 
> > > Public PGP key:
> > > 
> > > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > > http://ihavearrived.org/
> > > —
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128518920
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128525095
> > .
> 
> ## 
> 
> Beyond our ideas of right and wrong doing there is a field, I'll meet you
> there
> -- Rumi
> 
> Public PGP key:
> https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> http://ihavearrived.org/

## 

Beyond our ideas of right and wrong doing there is a field, I'll meet you
there
-- Rumi

Public PGP key:
https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
http://ihavearrived.org/

**Comment by jimsky7** [comment]
Ah, I see why it’s confusing.

What I means is “starting from a date.” If you requested date=20150801 then you would get everything from August 1st through today, including August 1st. This way you could catch up if you knew that your last data was from August 1st, and you’d only get what you need.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

---

Sky (Jim Schuyler, PhD)
—The future has arrived, and the label says “some assembly required.” 
Blog: http://blog.red7.com/
Phone: +1.415.759.7337
PGP Keys: http://web.red7.com/pgp

**Comment by SunyataZero** [comment]
I understand what you're saying about downloading all articles after a
given data. I made a mistake though when thinking about this before and
have now come up with another idea:
Why not send the id as a parameter instead of the date? Then there's no
risk of doubles right?

On Fri, Aug 7, 2015 at 1:07 AM, Sky notifications@github.com wrote:

> Ah, I see why it’s confusing.
> 
> What I means is “starting from a date.” If you requested date=20150801
> then you would get everything from August 1st through today, including
> August 1st. This way you could catch up if you knew that your last data was
> from August 1st, and you’d only get what you need.
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> CyberSpark.net
> -Keeping the flame of free speech
> and human rights alive online
> 
> ---
> 
> ---
> 
> Sky (Jim Schuyler, PhD)
> —The future has arrived, and the label says “some assembly required.”
> Blog: http://blog.red7.com/
> Phone: +1.415.759.7337
> PGP Keys: http://web.red7.com/pgp
> 
> > On Aug 6, 2015, at 4:02 PM, Tord notifications@github.com wrote:
> > 
> > Ok, great, one thing i'm worrying about though with using the date
> > instead
> > of a consecutivly updated id is that it's possible that two articles are
> > posted on the same day (though unlikely). The date will be important
> > though
> > since we have "search by date" but that's inside the application and we
> > have this already. I may be missing something but i'm not sure that we
> > need
> > to be able to send the date as a parameter to the atom feed (or what
> > produces the atom feed), does this make sense?
> > Kind Regards, Tord
> > 
> > On Fri, Aug 7, 2015 at 12:57 AM, Sky sky@red7.com wrote:
> > 
> > > The ID is indeed the database row number of the actual post. They’re
> > > not
> > > consecutive, as you noticed. They are unique, however.
> > > 
> > > I should be able to give you a feed-by-date capability in a few days.
> > > 
> > > ---
> > > 
> > > ---
> > > 
> > > ---
> > > 
> > > Sky (Jim Schuyler, PhD)
> > > —The future has arrived, and the label says “some assembly required.”
> > > Blog: http://blog.red7.com/
> > > Phone: +1.415.759.7337
> > > PGP Keys: http://web.red7.com/pgp
> > > 
> > > On Aug 6, 2015, at 3:46 PM, Tord Dellsén tord.dellsen@gmail.com
> > > wrote:
> > > 
> > > This is terrific! I'm very relieved to see that it's working. Yes, i'm
> > > thinking the same as you: The first time the app is launched i will
> > > download everything, and we'll have a variable storing the id or date
> > > of
> > > the latest article. Then we'll fetch the same number of articles as
> > > days
> > > that has passed since that date. In this way though there's a risk of
> > > problems like you said ("kludge" - what a funny word!). If we want to
> > > be
> > > sure we can fetch one extra and compare the id's of the latest we have
> > > with
> > > the oldest we fetch
> > > 
> > > Even better would be to have an id for each Metta where we can trust
> > > that
> > > the id is incremented by one for each Daily Metta article. There's
> > > already
> > > this tag
> > > <id>http://mettacenter.org/?p=16769</id>
> > > but that is increased more than one (i'm guessing it's for the
> > > mettacenter.org pages or blog posts in general right?). Maybe we could
> > > fix this when dealing with the xml update?
> > > 
> > > Kind Regards,
> > > Tord
> > > 
> > > On Fri, Aug 7, 2015 at 12:19 AM, Sky notifications@github.com wrote:
> > > 
> > > > I was able to modify the feeds URL so you can now say how many entries
> > > > you want. You could request a zillion the first time, then cut back
> > > > based
> > > > on the number of days you’ve gone without fetching. I believe you’d
> > > > call
> > > > that a kludge, wouldn’t you?
> > > > 
> > > > http://mettacenter http://mettacenter/.org
> > > > /category/daily-metta/feed/atom/?n=2
> > > > 
> > > > for example, would get you the most recent two Daily Mettas.
> > > > 
> > > > I would like to be able to do this by date, but I don’t have time to
> > > > look
> > > > into this today. Since I know I can pick up parameters from the URL,
> > > > and
> > > > can pick those up before the database query runs, I know it’s
> > > > possible. I
> > > > just have to investigate the proper params to add to the SQL query in
> > > > order
> > > > to handle dates.
> > > > 
> > > > Catch you later.
> > > > 
> > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > CyberSpark.net
> > > > -Keeping the flame of free speech
> > > > and human rights alive online
> > > > 
> > > > > On Aug 6, 2015, at 2:47 PM, Tord notifications@github.com wrote:
> > > > > 
> > > > > 209K for only 25 items?? Alright, at least what will be saved in
> > > > > the db
> > > > > is
> > > > > a lot less (roughly one fourth of that). I can see that the article
> > > > > text
> > > > > itself is repeated in the Atom feed, is this something that can be
> > > > > removed?
> > > > > Kind Regards, Tord
> > > > > 
> > > > > On Thu, Aug 6, 2015 at 11:42 PM, Sky notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > I was able to set the number of items returned in Atom/RSS/XML
> > > > > > feeds
> > > > > > to 25
> > > > > > today. It was a bit tricky and it affects all feeds, but does not
> > > > > > changed
> > > > > > the number of items returned "per page" within the actual web
> > > > > > site.
> > > > > > That
> > > > > > was the tricky part -- making sure it only affects the feed. I am
> > > > > > still
> > > > > > looking for a way you can add something to the feed URL itself to
> > > > > > change
> > > > > > the number of items returned, but for now it's 25 items that will
> > > > > > be
> > > > > > returned. Incidentally, the feed is currently 209K when it
> > > > > > includes 25
> > > > > > items, so this is not practical long term for mobile users.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > 
> > > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128517959
> > > > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Beyond our ideas of right and wrong doing there is a field, I'll
> > > > > meet
> > > > > you
> > > > > there
> > > > > -- Rumi
> > > > > 
> > > > > Public PGP key:
> > > > 
> > > > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > > > 
> > > > > http://ihavearrived.org/
> > > > > —
> > > > > Reply to this email directly or view it on GitHub <
> > > > 
> > > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128518920
> > > > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128525095
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Beyond our ideas of right and wrong doing there is a field, I'll meet
> > > you
> > > there
> > > -- Rumi
> > > 
> > > Public PGP key:
> > > 
> > > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > > http://ihavearrived.org/
> > 
> > ## 
> > 
> > Beyond our ideas of right and wrong doing there is a field, I'll meet you
> > there
> > -- Rumi
> > 
> > Public PGP key:
> > 
> > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > http://ihavearrived.org/
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128535220
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128535858
> .

## 

Beyond our ideas of right and wrong doing there is a field, I'll meet you
there
-- Rumi

Public PGP key:
https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
http://ihavearrived.org/

**Comment by jimsky7** [comment]
So kind of like asking “give me everything after ID=ddddd” ?

I could do that pretty easily. Keep in mind that you must already have at least one ID in order to utilize this kind of query. With dates, you would not need any prior data. And the first time, you can request just an n=something to at least get some data.

For this query

```
http://mettacenter.org/category/daily-metta/feed/atom/?n=10&ID=17060
```

If there are 15 items available with ID 17060 or higher, do you expect to receive only 10(because n=10) or do you expect 15? I would personally say you are going to get 10. I would “and” together the conditions.

-Sky

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online

**Comment by SunyataZero** [comment]
Can't tell you what a relief it is that this is working, it's been
bothering me for some time now

I'm not sure i understand everything you've written, but what i'm thinking
is that if we give just the n it's assumed that we take the n latest
articles and if we give a start-id we take all articles from the newest
until (and perhaps including) the given date. (If we do it this way we may
not even need the case where both parameters are given) Is this a good
approach?

Kind Regards,
Tord

On Fri, Aug 7, 2015 at 2:23 AM, Sky notifications@github.com wrote:

> So kind of like asking “give me everything after ID=ddddd” ?
> 
> I could do that pretty easily. Keep in mind that you must already have at
> least one ID in order to utilize this kind of query. With dates, you would
> not need any prior data. And the first time, you can request just an
> n=something to at least get some data.
> 
> For this query
> 
> http://mettacenter.org/category/daily-metta/feed/atom/?n=10&ID=17060
> 
> If there are 15 items available with ID 17060 or higher, do you expect to
> receive only 10(because n=10) or do you expect 15? I would personally say
> you are going to get 10. I would “and” together the conditions.
> 
> -Sky
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> CyberSpark.net
> -Keeping the flame of free speech
> and human rights alive online
> 
> > On Aug 6, 2015, at 4:34 PM, Tord notifications@github.com wrote:
> > 
> > I understand what you're saying about downloading all articles after a
> > given data. I made a mistake though when thinking about this before and
> > have now come up with another idea:
> > Why not send the id as a parameter instead of the date? Then there's no
> > risk of doubles right?
> > 
> > On Fri, Aug 7, 2015 at 1:07 AM, Sky notifications@github.com wrote:
> > 
> > > Ah, I see why it’s confusing.
> > > 
> > > What I means is “starting from a date.” If you requested date=20150801
> > > then you would get everything from August 1st through today, including
> > > August 1st. This way you could catch up if you knew that your last
> > > data was
> > > from August 1st, and you’d only get what you need.
> > > 
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > CyberSpark.net
> > > -Keeping the flame of free speech
> > > and human rights alive online
> > > 
> > > ---
> > > - -
> > >   - - - - - - - - - - - - - - - - - -
> > >   Sky (Jim Schuyler, PhD)
> > >   —The future has arrived, and the label says “some assembly required.”
> > >   Blog: http://blog.red7.com/
> > >   Phone: +1.415.759.7337
> > >   PGP Keys: http://web.red7.com/pgp
> > > 
> > > > On Aug 6, 2015, at 4:02 PM, Tord notifications@github.com wrote:
> > > > 
> > > > Ok, great, one thing i'm worrying about though with using the date
> > > > instead
> > > > of a consecutivly updated id is that it's possible that two articles
> > > > are
> > > > posted on the same day (though unlikely). The date will be important
> > > > though
> > > > since we have "search by date" but that's inside the application and
> > > > we
> > > > have this already. I may be missing something but i'm not sure that
> > > > we
> > > > need
> > > > to be able to send the date as a parameter to the atom feed (or what
> > > > produces the atom feed), does this make sense?
> > > > Kind Regards, Tord
> > > > 
> > > > On Fri, Aug 7, 2015 at 12:57 AM, Sky sky@red7.com wrote:
> > > > 
> > > > > The ID is indeed the database row number of the actual post.
> > > > > They’re
> > > > > not
> > > > > consecutive, as you noticed. They are unique, however.
> > > > > 
> > > > > I should be able to give you a feed-by-date capability in a few
> > > > > days.
> > > > > 
> > > > > ---
> > > > > - -
> > > > >   - - -
> > > > >   - - - - - - - - - - - - - - - - -
> > > > >   Sky (Jim Schuyler, PhD)
> > > > >   —The future has arrived, and the label says “some assembly
> > > > >   required.”
> > > > >   Blog: http://blog.red7.com/
> > > > >   Phone: +1.415.759.7337
> > > > >   PGP Keys: http://web.red7.com/pgp
> > > > > 
> > > > > On Aug 6, 2015, at 3:46 PM, Tord Dellsén tord.dellsen@gmail.com
> > > > > wrote:
> > > > > 
> > > > > This is terrific! I'm very relieved to see that it's working. Yes,
> > > > > i'm
> > > > > thinking the same as you: The first time the app is launched i will
> > > > > download everything, and we'll have a variable storing the id or
> > > > > date
> > > > > of
> > > > > the latest article. Then we'll fetch the same number of articles as
> > > > > days
> > > > > that has passed since that date. In this way though there's a risk
> > > > > of
> > > > > problems like you said ("kludge" - what a funny word!). If we want
> > > > > to
> > > > > be
> > > > > sure we can fetch one extra and compare the id's of the latest we
> > > > > have
> > > > > with
> > > > > the oldest we fetch
> > > > > 
> > > > > Even better would be to have an id for each Metta where we can
> > > > > trust
> > > > > that
> > > > > the id is incremented by one for each Daily Metta article. There's
> > > > > already
> > > > > this tag
> > > > > <id>http://mettacenter.org/?p=16769</id>
> > > > > but that is increased more than one (i'm guessing it's for the
> > > > > mettacenter.org pages or blog posts in general right?). Maybe we
> > > > > could
> > > > > fix this when dealing with the xml update?
> > > > > 
> > > > > Kind Regards,
> > > > > Tord
> > > > > 
> > > > > On Fri, Aug 7, 2015 at 12:19 AM, Sky notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > > I was able to modify the feeds URL so you can now say how many
> > > > > > entries
> > > > > > you want. You could request a zillion the first time, then cut
> > > > > > back
> > > > > > based
> > > > > > on the number of days you’ve gone without fetching. I believe
> > > > > > you’d
> > > > > > call
> > > > > > that a kludge, wouldn’t you?
> > > > > > 
> > > > > > http://mettacenter http://mettacenter/.org
> > > > > > /category/daily-metta/feed/atom/?n=2
> > > > > > 
> > > > > > for example, would get you the most recent two Daily Mettas.
> > > > > > 
> > > > > > I would like to be able to do this by date, but I don’t have time
> > > > > > to
> > > > > > look
> > > > > > into this today. Since I know I can pick up parameters from the
> > > > > > URL,
> > > > > > and
> > > > > > can pick those up before the database query runs, I know it’s
> > > > > > possible. I
> > > > > > just have to investigate the proper params to add to the SQL
> > > > > > query in
> > > > > > order
> > > > > > to handle dates.
> > > > > > 
> > > > > > Catch you later.
> > > > > > 
> > > > > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > > > > CyberSpark.net
> > > > > > -Keeping the flame of free speech
> > > > > > and human rights alive online
> > > > > > 
> > > > > > > On Aug 6, 2015, at 2:47 PM, Tord notifications@github.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > 209K for only 25 items?? Alright, at least what will be saved in
> > > > > > > the db
> > > > > > > is
> > > > > > > a lot less (roughly one fourth of that). I can see that the
> > > > > > > article
> > > > > > > text
> > > > > > > itself is repeated in the Atom feed, is this something that can
> > > > > > > be
> > > > > > > removed?
> > > > > > > Kind Regards, Tord
> > > > > > > 
> > > > > > > On Thu, Aug 6, 2015 at 11:42 PM, Sky notifications@github.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > I was able to set the number of items returned in Atom/RSS/XML
> > > > > > > > feeds
> > > > > > > > to 25
> > > > > > > > today. It was a bit tricky and it affects all feeds, but does
> > > > > > > > not
> > > > > > > > changed
> > > > > > > > the number of items returned "per page" within the actual web
> > > > > > > > site.
> > > > > > > > That
> > > > > > > > was the tricky part -- making sure it only affects the feed.
> > > > > > > > I am
> > > > > > > > still
> > > > > > > > looking for a way you can add something to the feed URL
> > > > > > > > itself to
> > > > > > > > change
> > > > > > > > the number of items returned, but for now it's 25 items that
> > > > > > > > will
> > > > > > > > be
> > > > > > > > returned. Incidentally, the feed is currently 209K when it
> > > > > > > > includes 25
> > > > > > > > items, so this is not practical long term for mobile users.
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > <
> > > 
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128517959
> > > 
> > > > > > > > .
> > > > > > > 
> > > > > > > ## 
> > > > > > > 
> > > > > > > Beyond our ideas of right and wrong doing there is a field, I'll
> > > > > > > meet
> > > > > > > you
> > > > > > > there
> > > > > > > -- Rumi
> > > > > > > 
> > > > > > > Public PGP key:
> > > 
> > > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > > 
> > > > > > > http://ihavearrived.org/
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub <
> > > 
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128518920
> > > 
> > > > > > > .
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > 
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128525095
> > > 
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Beyond our ideas of right and wrong doing there is a field, I'll
> > > > > meet
> > > > > you
> > > > > there
> > > > > -- Rumi
> > > > > 
> > > > > Public PGP key:
> > > 
> > > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > > 
> > > > > http://ihavearrived.org/
> > > > 
> > > > ## 
> > > > 
> > > > Beyond our ideas of right and wrong doing there is a field, I'll
> > > > meet you
> > > > there
> > > > -- Rumi
> > > > 
> > > > Public PGP key:
> > > 
> > > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > > 
> > > > http://ihavearrived.org/
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > 
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128535220
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128535858
> > > 
> > > .
> > 
> > ## 
> > 
> > Beyond our ideas of right and wrong doing there is a field, I'll meet you
> > there
> > -- Rumi
> > 
> > Public PGP key:
> > 
> > https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
> > http://ihavearrived.org/
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128539049
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MettaCenter/DailyMettaApp/issues/30#issuecomment-128547416
> .

## 

Beyond our ideas of right and wrong doing there is a field, I'll meet you
there
-- Rumi

Public PGP key:
https://keyserver.pgp.com/vkd/SubmitSearch.event?SearchCriteria=tord.dellsen@gmail.com
http://ihavearrived.org/

**Comment by jimsky7** [comment]
I’ll implement them (all) as limits. They will be ANDed together.

If n=NNN is specified, then a maximum of NNN items will be retrieved.

If id=DDDDD is specified, then every item retrieved will have an ID DDDDD or greater.

If date=YYYYMMDD is specified, then every item retrieved will be from that date or later.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CyberSpark.net
-Keeping the flame of free speech 
      and human rights alive online
